---
title: "Midterm project 678"
author: "Chi Zhang"
date: "2020/11/29"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(magrittr)
library(lubridate)
library(data.table)
library(wordcloud)
library(tm)
library(qdap)
library(corrplot)
library(rstan)
library(rstanarm)
library(lmerTest)
library(jtools)
library(sjPlot)
library(sjmisc)
library(glmmTMB)
library(car)
library(ggeffects)
```
#read data
```{r}
US_trending <- fread("USvideos.csv", encoding = 'UTF-8',header = T,blank.lines.skip=TRUE)
US_trending$trending_date <- ydm(US_trending$trending_date)
US_trending$description[is.na(US_trending$description)] <- " "
```


#top 20 chanel
```{r}
count_channel<-US_trending%>%group_by(US_trending$channel_title)%>%summarise(count=n())
top20_channel <- count_channel%>%arrange(desc(count)) %>% slice(1:20)
colnames(top20_channel)[1] <-"channel"
p2 <- ggplot(data=top20_channel,aes(x=channel,y=count,fill=channel))+geom_bar(stat = "identity")+labs(x="channel title",y="count",title = "Top 20 treanding video channels")+coord_flip()+ theme(legend.key.size = unit(10, "pt"))+ geom_text(aes(label = count, y= ..count..), stat= "count", hjust = 0,size=3)
p2
```
#top 20 tag
```{r}
count_tag <- data.frame(US_trending$tags)
count_tag <- gsub("[[:punct:]]", " ", count_tag)
count_tag <- data.frame(count_tag)
freq <- freq_terms(count_tag,top=20, at.least = 2,stopwords =tm::stopwords("english"))
freq <-data.frame(freq)
p3<-ggplot(data=freq,aes(x=WORD,y=FREQ,fill=WORD))+geom_bar(stat = "identity")+labs(x="Tag",y="count",title = "Top 20 treanding video tags")+coord_flip()+ theme(legend.key.size = unit(10, "pt"))+geom_text(aes(label = FREQ, y= ..count..), stat= "count", hjust = 0,size=3)
p3
```
#more tags
```{r,warning=FALSE}
freq100 <- freq_terms(count_tag,top=100, at.least = 2,stopwords =tm::stopwords("english"))
wordcloud(words = freq100$WORD, freq = freq100$FREQ,max.words =100,min.freq=3,scale=c(4,.5),random.order = FALSE,rot.per=.35,colors=palette(),width=1200, height=700)
```
#correlation
```{r}
corr <-US_trending[,c("views","likes","dislikes","comment_count")]
corr$views <-as.numeric(as.character(corr$views))
corr$likes <-as.numeric(as.character(corr$likes))
corr$dislikes <-as.numeric(as.character(corr$dislikes))
corr$comment_count <-as.numeric(as.character(corr$comment_count))
corr <-data.frame(corr)
matrix <- cor(corr,use = "complete.obs")
corrplot(corr=matrix, method ="color", order= "hclust", tl.col="black",addrect=3, addCoef.col="black", sig.level = 0.01, insig = "blank")
```
#data for model
```{r}
#top20channel <- subset(US_trending, channel_title %in% top20_channel$channel)
#data5 <- head(US_trending[order(-US_trending$views),], 5000)
data5 <- data.frame(US_trending[,5],US_trending[,8:11])
data5$views <-as.numeric(as.character(data5$views))
data5$likes <-as.numeric(as.character(data5$likes))
data5$dislikes <-as.numeric(as.character(data5$dislikes))
data5$comment_count <-as.numeric(as.character(data5$comment_count))
data5$category_id <-as.factor(data5$category_id)
```
#percentage of interactions
```{r}
viewsm <- mean(data5$views,na.rm = T)
likesm <- mean(data5$likes,na.rm = T)
dislikesm <- mean(data5$dislikes,na.rm = T)
commentm <- mean(data5$comment_count,na.rm = T)
var <- 1:3
percentage <- 1:3
data6 <- data.frame(var,percentage)
data6[,1] <- c("likes_per", "dislikes_per", "comment_per")
data6[,2] <- c(likesm /viewsm*100,dislikesm /viewsm*100,commentm /viewsm*100)

```
#bar chart of percentatge
```{r}
p4 <- ggplot(data6, aes(x=var, y=percentage, fill=var)) +
  geom_bar(stat="identity")+theme_minimal()+
  geom_text(aes(label=percentage), vjust=1, color="white", size=3.5)
p4
```
#histogram counts interactions
```{r}
p1 <- US_trending%>% ggplot(aes(x=US_trending$views)) + 
  geom_histogram(fill="blue",color="black",alpha=0.3)+xlim(0,5e6)+labs(x="views",y="count",title = "views distribution")
p1
```
```{r}
p5<-data5%>% ggplot(aes(x=data5$likes)) + 
  geom_histogram(fill="blue",color="black",alpha=0.3)+xlim(0,5e4)+labs(x="likes",y="count",title = "likes distribution")
p5
```

```{r}
p6<-data5%>% ggplot(aes(x=data5$dislikes)) + 
  geom_histogram(fill="blue",color="black",alpha=0.3)+xlim(0,5e3)+labs(x="dislikes",y="count",title = "dislikes distribution")
p6
```
```{r}
p7<-data5%>% ggplot(aes(x=data5$comment_count)) + 
  geom_histogram(fill="blue",color="black",alpha=0.3)+xlim(0,5e3)+labs(x="comment",y="count",title = "comment distribution")
p7
```
#density distribution of interactions
```{r}
p8 <-ggplot(data5, aes(x=views,fill="#FF6666")) +
  geom_density(alpha=0.4)+xlim(0,5e4)+labs(x="views",y="density",title = "views distribution")
p8
```
```{r}
p9 <-ggplot(data5, aes(x=likes,fill="#FF6666")) +
  geom_density(alpha=0.4)+xlim(0,5e2)+labs(x="likes",y="density",title = "likes distribution")
p9
```
```{r}
p10 <-ggplot(data5, aes(x=dislikes,fill="#FF6666")) +
  geom_density(alpha=0.4)+xlim(0,5e2)+labs(x="dislikes",y="density",title = "dislikes distribution")
p10
```
```{r}
p11 <-ggplot(data5, aes(x=comment_count,fill="#FF6666")) +
  geom_density(alpha=0.4)+xlim(0,5e2)+labs(x="comment",y="density",title = "comment distribution")
p11
```
```{r}
t.test(data5$dislikes, data5$likes)
```

#multiple linear model
```{r}
model1 = lm(views ~ likes + dislikes+ comment_count,data=data5)
summary(model1)
```
#residual plot of model1
```{r}
par(mfrow = c(2, 2))
plot(model1)

```
```{r}
confint(model1)
plot_model(model1,type = "diag",show.values = TRUE,value.offset = 0.5)
```

#multilevel model
```{r}
model2 <- lmer(views ~ likes + dislikes+ comment_count+ (1|category_id),data=data5)
summary(model2)
anova(model2)

```
#plots of model2
```{r}
par(mfrow = c(2, 2))
plot(model2)
plot_model(model2, type = "re",show.values = TRUE,value.offset = 0.5)

```
```{r}
plot_model(model2, type = "est",sort.est = TRUE,terms = "likes",show.values = TRUE)
plot_model(model2, type = "eff", terms = c("comment_count","category_id"))
plot_model(model2, type = "eff", terms = "dislikes",sort.est = TRUE)
plot_model(model2, type = "eff", terms = "comment_count")
plot_model(model2,type = "diag",show.values = TRUE,value.offset = 0.5)
ggplot(model2)

```

```{r}
effect_plot(model2, pred = likes, interval = TRUE,colors = "grey")
```
#poisson model
```{r}
model3 <- glm(views ~ likes + dislikes + comment_count, family="poisson", data=data5)
summary(model3)
```
```{r}
par(mfrow = c(2, 2))
plot(model3)
plot_model(model3,show.values = TRUE,value.offset = 0.5)
```

